version: '3'
services:
  
  postgresql:
    build: .
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports: 
      - 5434:5432

  openproject:
    image: openproject/community:10
    depends_on: 
      - postgresql
    environment:
      - POSTGRES_DATABASE_URL="postgresql://admin:admin@localhost:5434/openproject"
      - SECRET_KEY_BASE=secret
    ports:
      - 8081:80
  
  owncloud:
    image: owncloud
    restart: always
    depends_on: 
      - postgresql
    environment: 
      - OWNCLOUD_VERSION=latest
      - OWNCLOUD_DOMAIN=localhost
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - 8082:80
  
  gogs:
    image: gogs/gogs
    restart: always
    depends_on: 
      - postgresql
    ports:
      - 8083:3000
      